version: '3.9'

services:
  web:
    image: bohrium2b/moodlewp:latest
    container_name: elearn-wp-apache
    ports:
      - "8010:80"
    volumes:
      # Wordpress persistence
      - wp-plugins:/var/www/html/wp-content/plugins
      - wp-themes:/var/www/html/wp-content/themes
      # Moodle persistence
      - moodle-theme:/var/www/html/elearn/theme
      - moodle-mod:/var/www/html/elearn/mod
      - moodle-repository:/var/www/html/elearn/repository
      - moodle-local:/var/www/html/elearn/local
      - moodle-blocks:/var/www/html/elearn/blocks
      - moodle-data:/var/www/html/elearn/data
    depends_on:
      - db
    links:
      - db

  db:
    image: mariadb:11.3
    container_name: elearn-wp-db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: moodle_db
      MARIADB_USER: moodle_user
      MARIADB_PASSWORD: moodle_pw
    volumes:
      - dbdata:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d

volumes:
  wp-plugins:
  wp-themes:
  moodle-theme:
  moodle-mod:
  moodle-repository:
  moodle-local:
  moodle-blocks:
  moodle-data:
  dbdata: