name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'Dockerfile'
      - '.github/workflows/docker-image.yml'
      - '**/Dockerfile'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: bohrium2b/moodlewp
      IMAGE_TAG: latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if Dockerfile changed
        id: dockerfile_changed
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E '^Dockerfile$|(^|/)Dockerfile$'; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Log in to DockerHub
        if: steps.dockerfile_changed.outputs.changed == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        if: steps.dockerfile_changed.outputs.changed == 'true'
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .

      - name: Push Docker image
        if: steps.dockerfile_changed.outputs.changed == 'true'
        run: |
          docker push $IMAGE_NAME:$IMAGE_TAG

      - name: Skip build/push if Dockerfile has not changed
        if: steps.dockerfile_changed.outputs.changed != 'true'
        run: echo "Dockerfile did not change, skipping docker build and push."
